### ISSUE TITLE
Specified inputs are not in an expected order

### ISSUE THREAD

**Issue by moorepants** [csu-hmc/opty#111]
I think this TODO may relate: https://github.com/csu-hmc/opty/blob/master/opty/tests/test_direct_collocation.py#L180

Both Timo and I saw this when we started solving the bicycle problem with multiple inputs.

**Comment by moorepants** [comment]
See: https://github.com/brocksam/muscle-driven-bicycle-paper/pull/12#issuecomment-1704653531

**Comment by moorepants** [comment]
> See: brocksam/muscle-driven-bicycle-paper#12 (comment)

was not due to the `Problem.plot_trajectories()` method being incorrect but due to not using the internal order of the inputs that opty creates. I fixed that in the bicycle muscle paper.

**Comment by Peter230655** [comment]
I had a problem with plot_trajectories, see discussion #186.
I had 3 specified symbols (a torque acting on a ball) and one known trajectory (the time appearing explicitly in the EOMs).
What do I need to do?
**Thanks!**
