### ISSUE TITLE
Total value of the obj function

### ISSUE THREAD

**Issue by Peter230655** [csu-hmc/opty#124]
Let f(t) be the obj_function.
If I understand it correctly, $\int_0^{duration} f(t) dt$ should be minimized, at least in the two examples I saw.
Is this understanding correct?
If yes, is this value returned somewhere?
Thanks for any hint!

**Comment by moorepants** [comment]
The objective function (Python) returns this value.

**Comment by Peter230655** [comment]
My question was really STUPID!!! Sorry about it!
