### ISSUE TITLE
Errort message

### ISSUE THREAD

**Issue by Peter230655** [csu-hmc/opty#127]
I am trying to run a simulation with opzy, and I get this error message:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[9], [line 24](vscode-notebook-cell:?execution_count=9&line=24)
     [22](vscode-notebook-cell:?execution_count=9&line=22)     prob.add_option('max_iter', 3000)           # defaul is 3000
     [23](vscode-notebook-cell:?execution_count=9&line=23) # Find the optimal solution.
---> [24](vscode-notebook-cell:?execution_count=9&line=24)     solution, info = prob.solve(initial_guess)
     [25](vscode-notebook-cell:?execution_count=9&line=25)     print('message from optimizer:', info['status_msg'])
     [26](vscode-notebook-cell:?execution_count=9&line=26)     initial_guess = solution

File [c:\Users\Peter\anaconda3\envs\sympy-dev\Lib\site-packages\cyipopt\cython\ipopt_wrapper.pyx:621](file:///C:/Users/Peter/anaconda3/envs/sympy-dev/Lib/site-packages/cyipopt/cython/ipopt_wrapper.pyx:621), in ipopt_wrapper.Problem.solve()

ValueError: Wrong length of x0.

There is no variable x0 im my simulation.
What am I doing wrong?

Thanks!!

**Comment by moorepants** [comment]
I guess your initial guess has the wrong length.

**Comment by Peter230655** [comment]
Thanks!
I I understood from the inverted pendulum exampe, it should be: len(initial_guess) = len(state_symbols) * num_nodes + len(specified_symbols) * num_nodes.
If this is correct, then my initial guess seems to have the correct length.
stat_symbols = generalized coordinates + generalized speeds
specified_symbols = external forces, external torques.
Should attach my program here / send it to you?

**Comment by tjstienstra** [comment]
Are you sure that you specified all constant symbols?

**Comment by Peter230655** [comment]
My equation of motion has these free symbols: _EOM free symbold: {t, g, l, reibung, m}_
I specified all, except of course the time t:
state_symbols = tuple((*q_ind, *u_ind))
laenge = len(state_symbols)
print(state_symbols, len(state_symbols))
_constant_symbols = (l, m, g, reibung)_
specified_symbols = (Tx, Ty)

and I gave then values:

par_map = OrderedDict()
par_map[l]       = 2.0
par_map[m]       = 1.0
par_map[g]       = 9.81
par_map[reibung] = 0.

**Comment by tjstienstra** [comment]
Hmmm, that sounds good.

**Comment by Peter230655** [comment]
But does not work! :-(

**Comment by Peter230655** [comment]
Maybe I found the problem: My EOMs contain derivatives, which should not be there, maybe my kinematic equations are wrong.

**Comment by Peter230655** [comment]
I found the problem: I specified the specified_symbols as sm.symbols, and not as me.dynamicsymbols
