### ISSUE TITLE
Make args and kwargs in Problem explicit (so default values are shown)

### ISSUE THREAD

**Issue by Peter230655** [csu-hmc/opty#129]
This is optional, as I read the docs. _midpoint_ and _backward_ euler are available.
Which one is the default value? (I would assume, that the default method is normally better)

Thanks!

**Comment by moorepants** [comment]
The default is backward euler.

**Comment by moorepants** [comment]
It is clear here:

```
opty.direct_collocation.ConstraintCollocator(equations_of_motion, state_symbols, num_collocation_nodes, node_time_interval, known_parameter_map={}, known_trajectory_map={}, instance_constraints=None, time_symbol=None, tmp_dir=None, integration_method='backward euler', parallel=False)
```

But we don't expose that in `Problem`:

```
class opty.direct_collocation.Problem(obj, obj_grad, *args, **kwargs)
```

**Comment by Peter230655** [comment]
Thanks!!
I must admit, that I have no idea what
_opty.direct_collocation.ConstraintCollocator(equations_of_motion, state_symbols, num_collocation_nodes, node_time_interval, known_parameter_map={}, known_trajectory_map={}, instance_constraints=None, time_symbol=None, tmp_dir=None, integration_method='backward euler', parallel=False)_

means.

**Comment by moorepants** [comment]
Reopening because it would be better to have all the args and kwargs be explicit in `Problem`.

**Comment by moorepants** [comment]
`opty.direct_collocation.ConstraintCollocator(equations_of_motion, state_symbols, num_collocation_nodes, node_time_interval, known_parameter_map={}, known_trajectory_map={}, instance_constraints=None, time_symbol=None, tmp_dir=None, integration_method='backward euler', parallel=False)`

Is the signature for the `ConstraintCollocator` class. It shows what arguments and keyword arguments it accepts and for the keyword arguments it shows what the default values are.

**Comment by Peter230655** [comment]
I am ignorant in these things: What is the _ConstraintCollocator_ class?
Maybe too complicated to expalin to me.

**Comment by moorepants** [comment]
It is explained in the documentation: https://opty.readthedocs.io/en/latest/api.html#opty.direct_collocation.ConstraintCollocator

**Comment by Peter230655** [comment]
Even printed out on my desk, but I never looked at it, as in the examples only _Problem_ was used.
I need to learn more about the basic structure of things like opty.
