### ISSUE TITLE
Question about documentation

### ISSUE THREAD

**Issue by Peter230655** [csu-hmc/opty#135]
Am I right to assume that this:

https://opty.readthedocs.io/_/downloads/en/latest/pdf/

contains all the information / documentation about opty?
(So I do not have to ask too many dumb questions?)

Thanks!

**Comment by moorepants** [comment]
Yes, that is all the documentation of opty.

opty is built on top of cyipopt and ipopt, so you may be interested in the documentation for those too:

https://cyipopt.readthedocs.io/en/latest/

https://coin-or.github.io/Ipopt/

**Comment by Peter230655** [comment]
Thanks a lot!!
