### ISSUE TITLE
Question concerning the initial guess for solve(initial_guess)

### ISSUE THREAD

**Issue by Peter230655** [csu-hmc/opty#152]
Just to make sure I understood the documentation right:

N = number of collocation nodes
t0 = starting time for optimization
tf = final time for optimization
delta = (t0 - tf) / (N-1)
state_variables = [x, y, ux, uy], so
n = len(state_variables)

then the sequence in initial_guess is this:
initial_guess = [ x[t0], x[t0 + delta], ....., x[tf], y[t0]....,, y[tf], ....., uy[tf], same for input_trajectories, unknown parameters  ]
, and same sequence in free.

Is my understanding correct?
**Thanks!**

**Comment by moorepants** [comment]
I added this to the documentation:
![image](https://github.com/csu-hmc/opty/assets/276007/7486ab9f-6e1e-474c-86dd-21b81a4315d9)
