### ISSUE TITLE
A question about forming the EOMs

### ISSUE THREAD

**Issue by Peter230655** [csu-hmc/opty#167]
If I have a linear nonholonomic constraint, which results from a holonomic constraint, I form the EOMs for opty like this:
EOM = kinematic-differential equations / (fr + frstar) / holonomic constraint. ( / means col.join)

But what do I do if I have a real linear nonholonomic constraint, not reduceable to a holonomic constraint?
What would be the last equation(s)?

(What I did was this: I formed rhs = KM.rhs() and the set EOM = (rhs - y.diff(t), where y = [gen. coordinates, gen. speeds] 
This seemed to work, but does not look very elegant. Also KM.rhs() is very time consuming for larger problems)

**Thanks for any help!**

**Comment by tjstienstra** [comment]
You should be able to use `kdes / fr + frstart / hol_eqs / nonhol_eqs`

**Comment by Peter230655** [comment]
Thanks, I will try it!
( I tried it with a complex constraint, the result was utter garbage )
Would the sequence matter, that is
kdes / fr + frstar / hol_eqs / nonhol_eqs   _as good as_
kdes / fr + frstar / nonhol_eqs / hol_eqs  ?

**Thanks!**

**Comment by tjstienstra** [comment]
The order should officially not matter.

**Comment by Peter230655** [comment]
**Thanks!**
I will play around some more this evening - now even I have to work. :-(

**Comment by Peter230655** [comment]
It worked exactly like you said, also with my complex motion constraints!
**Thanks!**

**Comment by Peter230655** [comment]
It worked exactly like you said!
**Thanks!**
