### ISSUE TITLE
plot_trajectories errors if there are no input trajectories

### ISSUE THREAD

**Issue by Peter230655** [csu-hmc/opty#229]
There seems to be an error in this method:
If there are no input trajectories (like in the parameter estimation problem I am playing around with right now) it tries to put a title on a non existing axis; in line 421 of the code.

If you want me to, I will try to fix it and make a PR.

**Comment by moorepants** [comment]
> If you want me to, I will try to fix it and make a PR.

You are always welcome to do so.

Best to document it here with an example of failure, in case you don't fix it.

**Comment by Peter230655** [comment]
> > If you want me to, I will try to fix it and make a PR.
> 
> You are always welcome to do so.
> 
> Best to document it here with an example of failure, in case you don't fix it.

I am playing around with this parameter estimation idea you gave me; two independent measurements of the same motion...) and there are no input trajectories. This is how I noticed it. Then I looked at the code and it was clear.
This simulation would be the example.
When I make this PR should I also check for Derivative in the oems in the same PR or different PR?
B.t.w. : the simulation finds the true curve very accurately (with a few % deviation), but the parameter estimations are way off!
Unknown parameters should be at the end of the solution.

**Comment by Peter230655** [comment]
> > > If you want me to, I will try to fix it and make a PR.
> > 
> > 
> > You are always welcome to do so.
> > Best to document it here with an example of failure, in case you don't fix it.
> 
> I am playing around with this parameter estimation idea you gave me; two independent measurements of the same motion...) and there are no input trajectories. This is how I noticed it. Then I looked at the code and it was clear. This simulation would be the example. When I make this PR should I also check for Derivative in the oems in the same PR or different PR? Both are just 2 - 3 lines of code in my opinion.
B.t.w. : the simulation finds the true curve very accurately (with a few % deviation), but the parameter estimations are way off! Unknown parameters should be at the end of the solution, right?

**Comment by moorepants** [comment]
>  When I make this PR should I also check for Derivative in the oems in the same PR or different PR?

In general, you should make one PR per issue or one PR per idea. Mixing up things in a PR make it hard to review and thing about.

**Comment by Peter230655** [comment]
Makes sense! Will do so soon.

**Comment by moorepants** [comment]
Fixed by #231.
