### ISSUE TITLE
Wrong time step width in plots generated by Problem.plot_trajectories()

### ISSUE THREAD

**Issue by chris-konrad** [csu-hmc/opty#282]
[The time array for trajectory plotting](https://github.com/csu-hmc/opty/blob/aae009e48f1c1e9d19f43b12c650929622b0a510/opty/direct_collocation.py#L399) created by Problem.plot_trajectories() covers the interval [0, `num_collocation_nodes * node_time_interval`] including the limits while forcing the array size to be `num_collocation_nodes`. As a result, the time spacing is not as expected. This is the default behaviour of `np.linspace()`. Should be fixed by using `np.arange()` instead.

Example for `num_collocation_nodes = 5`, `node_time_interval=1`:
```
In[2]: np.linspace(0, num_collocation_nodes * node_time_interval, num=num_collocation_nodes)
Out[2]: array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In[3]: np.arange(0, num_collocation_nodes * node_time_interval, node_time_interval)
Out[3]: array([0, 1, 2, 3, 4])
```

In the linspace version, the time steps of the resulting array are not 1, which however would be expected because of `node_time_interval=1`.

**Comment by Peter230655** [comment]
As I know it, the final time is defined as tf = node_time_interval * (num_collection_nodes **- 1**),
you defined it as tf = node_time_interval * num_collection_nodes

**Comment by chris-konrad** [comment]
That would fix the problem as well. But it is currently not implemented that way (see: [/opty/direct_collocation.py#L400](https://github.com/csu-hmc/opty/blob/aae009e48f1c1e9d19f43b12c650929622b0a510/opty/direct_collocation.py#L400))

**Comment by Peter230655** [comment]
Maybe you are rigt, but all the examples I ever saw, the final time was defined a interval * (num-nodes **- 1**), assuming the starting time is zero.

**Comment by chris-konrad** [comment]
Have a look at [np.arange(start, stop, step)](https://numpy.org/doc/2.2/reference/generated/numpy.arange.html). It defines the interval as [start,stop). In `np.arange(0, num_collocation_nodes * node_time_interval)`,  the end of the interval is `stop = num_collocation_nodes * node_time_interval = 5`. But this will not be included in the time array. It stops at 4: 
```
In[3]: np.arange(0, num_collocation_nodes * node_time_interval, node_time_interval)
Out[3]: array([0, 1, 2, 3, 4])
```
