### ISSUE TITLE
Dockerfile: cannot find ipopt (cyipopt) 0.1.7

### ISSUE THREAD

**Issue by chrisdembia** [csu-hmc/opty#51]
The Dockerfile command `RUN cd /home/opty/opty && /home/opty/miniconda/envs/test-environment/bin/python setup.py install` causes the following error:

```
No local packages or working download links found for ipopt>=0.1.7
error: Could not find suitable distribution for Requirement.parse('ipopt>=0.1.7')
```

**Comment by moorepants** [comment]
I forgot that there was a Dockerfile. I'll just delete that. Preferred installation method is conda.
