### ISSUE TITLE
Improve the high level summary

### ISSUE THREAD

**Issue by moorepants** [csu-hmc/opty#59]
From: https://github.com/openjournals/joss-reviews/issues/300#issuecomment-325696614

> A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience — current summary is written in highly technical language, I suggest a lay introduction followed by a more detailed technical description of the software that includes equations to clarify what types of problems are applicable for the software

**Comment by moorepants** [comment]
@tvdbogert Would you say this is now addressed?

**Comment by tvdbogert** [comment]
Yes, but there are still a few gaps in the table (in the rows you added).

**Comment by moorepants** [comment]
This specific review comment didn't ask for the table, so I'm going to close this one.
