### ISSUE TITLE
Look into pyomo

### ISSUE THREAD

**Issue by moorepants** [csu-hmc/opty#85]
Just rediscovered this and noticed it  uses sympy under the hood for things. Should investigate comparisons to opty.

http://www.pyomo.org/

**Comment by billtubbs** [comment]
Have you seen this list of trajectory optimization software on wikipedia?
- https://en.wikipedia.org/wiki/Trajectory_optimization#Software

Is it worth adding opty to this list?

**Comment by moorepants** [comment]
You are welcome to add it to wikipedia if you think it fits there.
