### ISSUE TITLE
I can't install opty with Anaconda when the Python version is > 3.6

### ISSUE THREAD

**Issue by billtubbs** [csu-hmc/opty#90]
I tried with Python 3.8 and 3.7 using the following (in Terminal on OS X):

```
conda create --name opty37 python=3.7 opty pydy
```

and got these kind of messages from conda:

```
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                             

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package numpy conflicts for:
opty -> numpy[version='>=1.8.1']
opty -> cyipopt[version='>=0.1.7'] -> numpy[version='1.10.*|1.11.*|1.12.*|>=1.14.6,<2.0a0|>=1.16.5,<2.0a0|>=1.18.5,<2.0a0|>=1.19.2,<2.0a0|>=1.18.4,<2.0a0|>=1.18.1,<2.0a0|>=1.9.3,<2.0a0|>=1.9|>=1.11.3,<2.0a0|>=1.11|1.13.*|>=1.16.6,<2.0a0|>=1.15.1,<2.0a0']

Package scipy conflicts for:
opty -> scipy[version='>=0.14.1']
opty -> cyipopt[version='>=0.1.7'] -> scipy

Package python conflicts for:
opty -> cyipopt[version='>=0.1.7'] -> python[version='3.4.*|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0']
pydy -> numpy[version='>=1.11.0'] -> python[version='>=3.5,<3.6.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
opty -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']
pydy -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|3.4.*']
python=3.7

Package numpy-base conflicts for:
opty -> numpy[version='>=1.8.1'] -> ... etc.

```

But it works fine with Python 3.6:
```
conda create --name opty python=3.6 opty pydy
```

The installation instructions don't specify a Python version (it says 3.6+).  Is this a conda problem, or am I doing something wrong, or should I actually stick to 3.6 for now?

[My `conda --version` = 4.9.2]

**Comment by billtubbs** [comment]
This could be an issue with my Anaconda installation.  I am currently investigating and will delete and/or you can close this issue if that is the case.  Sorry for any inconvenience.

**Comment by billtubbs** [comment]
You can close this issue.  There is something wrong with my Anaconda installation that is creating problems. Sorry for any inconvenience.

**Comment by moorepants** [comment]
The conda forge opty feedstock has not been built with Python > 3.6. See:

https://github.com/conda-forge/opty-feedstock

We need to update that feedstock to get it working with the latest versions.

**Comment by moorepants** [comment]
I've opened: https://github.com/conda-forge/opty-feedstock/pull/15 and will try to get the builds running and updated packages.

**Comment by moorepants** [comment]
If you are installing opty from conda-forge for Py 3.6, 3.7, and 3.8 on Linux or OSX, it should work now. The PR referenced above has been merged. The packages should be available within an hour.

**Comment by billtubbs** [comment]
Thanks.  I just tried it again and it worked for Python 3.7 but not for 3.8.  3.7 is fine for me.  Don't go to any trouble for my benefit.

**Comment by moorepants** [comment]
This should work on osx:

```
conda create -n opty38  -c conda-forge python=3.8 opty
```

If it doesn't please report the error messages you get.

**Comment by moorepants** [comment]
Closing, since no updates.
