### ISSUE TITLE
instance_constraint_function_atoms also catches trigonometric functions

### ISSUE THREAD

**Issue by TJStienstra** [csu-hmc/opty#97]
[`all_funcs = all_funcs.union(con.atoms(sm.Function))`](https://github.com/csu-hmc/opty/blob/0a74a7a08ebd8bc0158e202640d9ad3d010c2d30/opty/direct_collocation.py#L769) used to find the functions used in instance constraints also catches trigonometric functions like `sin`, `cos`. These found functions are later used to determine the `closest_free_index`. This results in `sin(x(0.5))` to be used, while `x(0.5)` was expected. Have to say that I honestly find it a bit dangerous way that the original argument of a function will always have been time. A better approach then just grabbing every function is to only grab those functions, that were also detected as being time varying.

**Comment by TJStienstra** [comment]
This will have to be updated on multiple locations as `con.atoms(sm.Function)` is used quite a lot.

**Comment by moorepants** [comment]
If I remember correctly an instance constraint should only be set to a numerical value. It isn't clear what you are trying that would cause trig functions to show up. The code is only designed to handle things like `x(1.2) - 5.0`, i.e. no symbolics involved.
