### ISSUE TITLE
Invalid bounds are ignored without raising a warning or an error

### ISSUE THREAD

**Issue by tjstienstra** [csu-hmc/opty#99]
While debugging one of my own problems. I finally found out one of the reasons it was invalid, namely my bound was just being ignored as it was not directly a normal parameter. I would prefer that instead an error is raised, which can easily be done by adding an else statement [here](https://github.com/csu-hmc/opty/blob/0a74a7a08ebd8bc0158e202640d9ad3d010c2d30/opty/direct_collocation.py#L170).

**Comment by moorepants** [comment]
Seems like a good suggestion.

**Comment by moorepants** [comment]
This has been fixed at some point.
